{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE RecordWildCards #-}

module Data.Beatmap.FxTap.Put where

import Data.Beatmap.FxTap (FxTap (..), Note (..))
import Data.Binary.Put (
    Put,
    putCharUtf8,
    putDoublebe,
    putDoublele,
    putInt16be,
    putInt16le,
    putInt8,
    putStringUtf8,
 )
import Data.Foldable (for_)
import Data.List (intercalate)
import GHC.ByteOrder (ByteOrder (..))

putFxTapBinary :: ByteOrder -> FxTap -> Put
putFxTapBinary bo FxTap{..} = do
    putStringUtf8 "FXT@2601"

    putDouble overallDifficulty

    let title' = take 255 title
    putInt8 (fromIntegral (length title'))
    putStringUtf8 title'

    let artist' = take 255 artist
    putInt8 (fromIntegral (length artist'))
    putStringUtf8 artist'

    putInt8 (fromIntegral (length noteColumns))
    for_ noteColumns $ \notesColumn ->
        putInt16 (fromIntegral (length notesColumn))

    for_ noteColumns $ \notesColumn ->
        for_ notesColumn $ \case
            Tap{accumulatedStartTime} -> do
                putInt16 (fromInteger accumulatedStartTime)
                putInt16 0
            Hold{accumulatedStartTime, duration} -> do
                putInt16 (fromInteger accumulatedStartTime)
                putInt16 (fromInteger duration)
  where
    putDouble = case bo of LittleEndian -> putDoublele; BigEndian -> putDoublebe
    putInt16 = case bo of LittleEndian -> putInt16le; BigEndian -> putInt16be

putFxTapCSource :: String -> String -> FxTap -> Put
putFxTapCSource includeName symbolName FxTap{..} = do
    putStringUtf8 "// Generated by fxTap Adapter (fxta)\n"
    putStringUtf8 "#include <fxTap/beatmap.h>\n"

    let escapedIncludeName = includeName >>= \case; '\"' -> "\\\""; c -> pure c

    putStringUtf8 $ "#include \"" ++ escapedIncludeName ++ ".h\"\n"
    putCharUtf8 '\n'

    let columnCount = length noteColumns
    let noteCount = show (sum (map length noteColumns))
    let columnsLengths = map length noteColumns

    putStringUtf8 $ "FXT_Note " ++ symbolName ++ "_Notes" ++ "[" ++ noteCount ++ "] = {"

    for_ noteColumns $ \noteColumn ->
        for_ noteColumn $ \note -> do
            putStringUtf8 "{"
            case note of
                Tap{accumulatedStartTime} -> do
                    putStringUtf8 $ show accumulatedStartTime
                    putStringUtf8 ",0"
                Hold{accumulatedStartTime, duration} -> do
                    putStringUtf8 $ show accumulatedStartTime
                    putStringUtf8 ","
                    putStringUtf8 $ show duration
            putStringUtf8 "},"

    putStringUtf8 "};\n"

    putCharUtf8 '\n'

    putStringUtf8 $ "const FXT_Beatmap " ++ symbolName ++ "_Beatmap = {\n"

    do
        putStringUtf8 $ "\t.Title = " ++ show title ++ ",\n"
        putStringUtf8 $ "\t.Artist = " ++ show artist ++ ",\n"
        putStringUtf8 $ "\t.OverallDifficulty = " ++ show overallDifficulty ++ ",\n"
        putStringUtf8 $ "\t.ColumnCount = " ++ show columnCount ++ ",\n"
        putStringUtf8 $ "\t.ColumnSize = {" ++ intercalate "," (map show columnsLengths) ++ "},\n"

    do
        putStringUtf8 "\t.Notes = {\n"

        let offsets = take columnCount (scanl (+) 0 columnsLengths)

        for_ offsets $ \offset -> do
            putStringUtf8 $ "\t\t" ++ symbolName ++ "_Notes" ++ " + " ++ show offset ++ ",\n"

        putStringUtf8 "\t},\n"

    putStringUtf8 "};\n"

putFxTapCHeader :: String -> FxTap -> Put
putFxTapCHeader symbolName FxTap{noteColumns} = do
    putStringUtf8 "// Generated by fxTap Adapter (fxta)\n"
    putStringUtf8 "#pragma once\n"
    putCharUtf8 '\n'
    putStringUtf8 "#include <fxTap/beatmap.h>\n"
    putCharUtf8 '\n'

    let columnsLengths = show (sum (map length noteColumns))

    putStringUtf8 $ "extern FXT_Note " ++ symbolName ++ "_Notes" ++ "[" ++ columnsLengths ++ "];\n"
    putStringUtf8 $ "extern const FXT_Beatmap " ++ symbolName ++ "_Beatmap;\n"
